#!------------------------------------
#? Configuracion de un Deployment para el HaProxy
#? Santiago Arellano 00328370
#? Esta es la tercera configuracion de un Deployment en el cluster
#? La idea es que no queria tener toda la configuracion en un mismo Deployment
#? y para exploprar los objetos de Kbuernete, necesitaba crear diferentes archivos.
#? Esta configuracion incluye el Deployment y la configuracion con ConfigMaps.
#! -----------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    # Infrastructure information
    infrastructure.deployment.config.type: "base-config"
    infrastructure.deployment.config.name: "base-config-dockerized-nfvs"
    infrastructure.deployment.config.author: "Santiago Arellano"
    infrastructure.deployment.config.revision: "Rev-1.0.0-alpha"
    # Configuration Information
    application.deployment.config.type: "default-behavior-config"
    application.deployment.config.name: "agricommerce-base-behavior-config"
    application.deployment.config.author: "Santiago Arellano"
    application.deployment.config.revision: "Rev-1.0.0-alpha"
  name: haproxy-configmap-haproxycfg
  namespace: networking-engineering-dockerized-nvf-project
data:
  haproxy.cfg: |
    global
    log stdout format raw local0

    defaults
        log global
        mode http
        option httplog
        option dontlognull
        timeout connect 5000
        timeout client 50000
        timeout server 50000

    frontend https_front
        bind *:443 ssl crt /etc/haproxy/agricommerce.pem
        # Route ALL requests through ModSecurity first
        default_backend modsecurity_back

    frontend http_front
        bind *:8080
        default_backend modsecurity_back

    backend modsecurity_back
        server modsecurity modsecurity:8080 check

    backend frontend_back
        server frontend frontend:34771 check

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy
  namespace: networking-engineering-dockerized-nvf-project
spec:
  replicas: 1
  selector:
    matchLabels:
      container.level.application.association: "agricommerce-haproxy"
      container.level.application.revision: "Rev-1.0.0-component-alpha"
  template:
    metadata:
      labels:
        container.level.application.association: "agricommerce-haproxy"
        container.level.application.revision: "Rev-1.0.0-component-alpha"
    spec:
      containers:
        - name: haproxy
          image: haproxy:2.9
          ports:
            - containerPort: 8080
            - containerPort: 443
          volumeMounts:
            - name: haproxy-configmap-haproxycfg
              mountPath: /usr/local/etc/haproxy/haproxy.cfg
              subPath: haproxy.cfg
            - name: haproxy-secret-agricommerce-cert
              mountPath: /etc/haproxy
          resources:
            requests:
              cpu: "300m"
              memory: "1Gi"
            limits:
              cpu: "500m"
              memory: "2Gi"
      volumes:
        - name: haproxy-configmap-haproxycfg
          configMap:
            name: haproxy-configmap-haproxycfg
        - name: haproxy-secret-agricommerce-cert
          secret:
            secretName: haproxy-secret-agricommerce.pem