apiVersion: v1
kind: Service
metadata:
  annotations:
    # Infrastructure information
    infrastructure.deployment.config.type: "base-config"
    infrastructure.deployment.config.name: "base-config-dockerized-nfvs"
    infrastructure.deployment.config.author: "Santiago Arellano"
    infrastructure.deployment.config.revision: "Rev-1.0.0-alpha"
    # Configuration Information
    application.deployment.config.type: "default-behavior-config"
    application.deployment.config.name: "agricommerce-base-behavior-config"
    application.deployment.config.author: "Santiago Arellano"
    application.deployment.config.revision: "Rev-1.0.0-alpha"
  name: frontend
  namespace: networking-engineering-dockerized-nvf-project
spec:
  selector:
    container.level.application.association: "agricommerce-frontend"
    container.level.application.revision: "Rev-1.0.0-component-alpha"
  ports:
    - name: http-for-frontend
      port: 34771
      targetPort: 34771
      protocol: TCP
  type: ClusterIP